### ISSUE TITLE
Compose port forwarding error

### ISSUE THREAD

**Issue by Dimariqe** [w0rng/amnezia-wg-easy#2]
Change:
      - "${WG_PORT}:51820/udp"
To:
      - "${WG_PORT}:${WG_PORT}/udp"
In:
https://github.com/w0rng/amnezia-wg-easy/blob/master/docker-compose.yml#L13

**Comment by w0rng** [comment]
Thanks for your issues. Fixed it in this commit: https://github.com/w0rng/amnezia-wg-easy/commit/3aeb551516919607d63a8d1141a339f5314cd913
