### ISSUE TITLE
Compatibility with default wireguard

### ISSUE THREAD

**Issue by s0rl0v** [w0rng/amnezia-wg-easy#6]
Hello @w0rng ,

Thank you for your work on bringing these great projects together, really apprciate it.

I suppose as of now amnezia-wg-easy server is not compatible with original wireguard protocol clients?

**Comment by w0rng** [comment]
Hello @s0rl0v 

Thank you for your kind words, I really appreciate it!

Amnezia is indeed compatible with the original WireGuard protocol as long as all additional parameters (JC, JCMIN, JCMAX, etc.) are set to 0. However, to make things easier, the Amnezia team has created forks of all the WireGuard clients, so this shouldn't be an issue. You can find these clients on GitHub: https://github.com/amnezia-vpn, and they are also available in all app stores.

**Comment by s0rl0v** [comment]
Thank you! This answers my question.
 I thought that it's possible to have wg and awg clients on the same server, but alas
Have a great day :)
